### ISSUE TITLE
Recreate test and train partitions for comparability

### ISSUE THREAD

**Issue by oskoller** [yunigma/Kaldi-for-ASR-of-Swiss-German#1]
It is currently not possible to recreate your used test and train partitioning. I cannot find the json file used for that anywhere in the repo.

$data/meta_info/test_set.json

Can you point me to where I can find this file?

Or is it the same splitting as https://github.com/tannonk/two-headed-master/blob/master/archimob/test_set_utts.json ?

Thanks a lot!

**Comment by yunigma** [comment]
Hi
yes, exactly, you can get the split from [https://github.com/tannonk/two-headed-master/blob/master/archimob/test_set_utts.json](url)

Thanks for pointing out!

**Comment by oskoller** [comment]
Thanks!
